version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my-mongo-db
    ports:
      - "27017:27017"       # Expose MongoDB on the host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root    # MongoDB root user
      MONGO_INITDB_ROOT_PASSWORD: example # MongoDB root password
    volumes:
      - mongo_data:/data/db  # Persistent volume for MongoDB data

volumes:
  mongo_data:
    driver: local             # Local volume driver

