# Use an official Golang runtime as the base image
FROM golang:1.23-alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy the Go modules manifests
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum are not changed
RUN go mod download

# Copy the entire Go project
COPY . .

# Expose port 8080
EXPOSE 8080

# Run the Go application
CMD ["go", "run", "."]

