// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: protobufs/workloadApi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChannelId string `protobuf:"bytes,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
}

func (x *WorkloadRequest) Reset() {
	*x = WorkloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_workloadApi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRequest) ProtoMessage() {}

func (x *WorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_workloadApi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRequest.ProtoReflect.Descriptor instead.
func (*WorkloadRequest) Descriptor() ([]byte, []int) {
	return file_protobufs_workloadApi_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type WorkloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkloadHandlerUrl string `protobuf:"bytes,1,opt,name=WorkloadHandlerUrl,proto3" json:"WorkloadHandlerUrl,omitempty"` // Use a field number instead of a string literal
}

func (x *WorkloadResponse) Reset() {
	*x = WorkloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufs_workloadApi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadResponse) ProtoMessage() {}

func (x *WorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufs_workloadApi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadResponse.ProtoReflect.Descriptor instead.
func (*WorkloadResponse) Descriptor() ([]byte, []int) {
	return file_protobufs_workloadApi_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadResponse) GetWorkloadHandlerUrl() string {
	if x != nil {
		return x.WorkloadHandlerUrl
	}
	return ""
}

var File_protobufs_workloadApi_proto protoreflect.FileDescriptor

var file_protobufs_workloadApi_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x77, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x77,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x69, 0x22, 0x2f, 0x0a, 0x0f, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x10, 0x57,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2e, 0x0a, 0x12, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x57, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x32,
	0x5b, 0x0a, 0x0b, 0x59, 0x6f, 0x75, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c,
	0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x69, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x69, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufs_workloadApi_proto_rawDescOnce sync.Once
	file_protobufs_workloadApi_proto_rawDescData = file_protobufs_workloadApi_proto_rawDesc
)

func file_protobufs_workloadApi_proto_rawDescGZIP() []byte {
	file_protobufs_workloadApi_proto_rawDescOnce.Do(func() {
		file_protobufs_workloadApi_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufs_workloadApi_proto_rawDescData)
	})
	return file_protobufs_workloadApi_proto_rawDescData
}

var file_protobufs_workloadApi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufs_workloadApi_proto_goTypes = []any{
	(*WorkloadRequest)(nil),  // 0: workloadApi.WorkloadRequest
	(*WorkloadResponse)(nil), // 1: workloadApi.WorkloadResponse
}
var file_protobufs_workloadApi_proto_depIdxs = []int32{
	0, // 0: workloadApi.YourService.createWorload:input_type -> workloadApi.WorkloadRequest
	1, // 1: workloadApi.YourService.createWorload:output_type -> workloadApi.WorkloadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufs_workloadApi_proto_init() }
func file_protobufs_workloadApi_proto_init() {
	if File_protobufs_workloadApi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufs_workloadApi_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*WorkloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufs_workloadApi_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WorkloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufs_workloadApi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufs_workloadApi_proto_goTypes,
		DependencyIndexes: file_protobufs_workloadApi_proto_depIdxs,
		MessageInfos:      file_protobufs_workloadApi_proto_msgTypes,
	}.Build()
	File_protobufs_workloadApi_proto = out.File
	file_protobufs_workloadApi_proto_rawDesc = nil
	file_protobufs_workloadApi_proto_goTypes = nil
	file_protobufs_workloadApi_proto_depIdxs = nil
}
